server:
  port: 8765
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  
spring:
  application:
    name: gateway-server
  cloud:
    config:
      uri: http://localhost:8888
      
zuul:
  RibbonRoutingFilter:
    route:
      disable:  false
  sensitiveHeaders: Cookie,Set-Cookie # Pass Authorization header downstream